#!/bin/bash

export RETRYONFAIL=1
export PATH=$PATH:$PWD
. .demoscript

set -e

comment "Demo assumes you have an ACA env already created"

rm -rf testDir2
doit mkdir testDir2
doit cd testDir2
cd testDir2

doit --noscroll azx init -g default -s fe108f6a-2bd6-409c-8bfb-8f21dbb7ba0a -l EastUS
doit azx add aca-redis -n redis2 --environment demo
doit azx add aca-app -n app2 -i duglin/aca-lister --external --bind redis2
doit azx up
doit ls .azx/stage_default
doit azx show aca-app -n app2
doit azx show aca-app -n app2 -o raw
doit azx show aca-redis -n redis2
doit azx down --wait
doit azx up
doit azx update aca-app -n app2 --unbind redis2
doit azx show aca-app -n app2
doit azx show aca-app -n app2 -o raw
doit azx up
doit azx down
