#!/bin/bash

export RETRYONFAIL=1
. .demoscript

clear
set -e

rm -rf testDir
doit mkdir testDir
doit cd testDir
doit ls -la

doit azx init
doit ls -la
comment normally we\'d ask for the subscription and resourceGroup

doit azx add aca-app -n myapp -i duglin/aca-redis 
comment go look at the app

doit cat ./azx/stage_default/aca-app-redis.json

doit azx add aca-redis -n myredis --provision

doit azx update aca-app -n myapp --bind myredis -provision
comment go look at the app

doit azx down
comment go look at the apps in the portal

doit azx up
